---
title: "Brain Somatic variants and aging"
subtitle: 'PsychAD aging data'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: true
---

<!---

system("rm -rf aging_testing_cache/")
rmarkdown::render("aging_testing.Rmd");


--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```


```{r load, cache=FALSE}
library(glmmTMB)
library(lme4)
library(tidyverse)
library(ggplot2)
library(parallel)
library(kableExtra)
library(lmerTest)

control_data = readRDS("~/Downloads/Aging_data_all_CellType.rds")
```

### Somatic variants versus callable sites
```{r Callable_Sites}
ggplot(control_data, aes(Callable_Sites, Count+.5, color=log(no_reads))) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1) +
  facet_wrap(~CellType)

ggplot(control_data, aes(CellType, Callable_Sites)) +
  geom_violin() +  
  geom_boxplot(width=.1) +
  scale_y_log10() +
  theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1)
```

### Fit regression models for each cell type
```{r regression}
ctrl = glmmTMBControl(optimizer=optim, optArgs=list(method="BFGS"))

resList = mclapply( unique(control_data$CellType), function(CT){

  keep = control_data$CellType == CT
  data = control_data[keep,]
  tab = table(data$SubID.x)
  include = names(tab)[tab > 1]
  data = data[data$SubID.x %in% include,]
  
  # glmmTMB
  form = Count ~ offset(log(Callable_Sites)) + (1|SubID.x) + log(no_cells) + log(no_reads)

  fit0 <- glmmTMB(form, family=nbinom2, data, control=ctrl)
  fitNull <- update(fit0, ~ . + PMI  + Sex + Brain_bank + (1|Ethnicity))
  fitLinear = update(fitNull, ~ . + Age)
  fitQuad = update(fitLinear, ~ . + I(Age^2))

  list(CellType = CT, 
        data = data,
        fit0 = fit0, 
        fitNull = fitNull, 
        fitLinear = fitLinear, 
        fitQuad = fitQuad)
}, mc.cores=6)
```

# Hypothesis testing
```{r tests}
resLinear = lapply(resList, function(x){
  df = coef(summary(x$fitLinear))$cond["Age",]
  data.frame(CellType = x$CellType, t(df))
  })
resLinear = do.call(rbind, resLinear) %>%
            rename(p.value = Pr...z..) %>%
            mutate(FDR = p.adjust(p.value, "fdr"))

resLinear %>%
  mutate(CellType = factor(CellType, CellType)) %>%
  ggplot(aes(CellType, Estimate, color=CellType)) +
    geom_point() +
    geom_errorbar(aes(ymin = Estimate - 1.96*Std..Error, ymax = Estimate + 1.96*Std..Error), width=0) +
    geom_text(aes(CellType, .03, label=format(FDR, digits=3)), color="black") +
    theme_classic() +
    theme(aspect.ratio=1, legend.position="none") +
    geom_hline(yintercept=0, linetype="dashed") +
    coord_flip() +
    ggtitle("Linear")

resLinear %>%
  mutate( p.value = format(p.value, scientific=TRUE)) %>%
  kbl %>% 
  kable_classic(full_width = FALSE)

resQuad = lapply(resList, function(x){
  df = coef(summary(x$fitQuad))$cond["Age",]
  data.frame(CellType = x$CellType, t(df))
  })
resQuad = do.call(rbind, resQuad) %>%
            rename(p.value = Pr...z..) %>%
            mutate(FDR = p.adjust(p.value, "fdr"))

resQuad %>%
  mutate(CellType = factor(CellType, CellType)) %>%
  ggplot(aes(CellType, Estimate, color=CellType)) +
    geom_point() +
    geom_errorbar(aes(ymin = Estimate - 1.96*Std..Error, ymax = Estimate + 1.96*Std..Error), width=0) +
    geom_text(aes(CellType, .03, label=format(FDR, digits=3)), color="black") +
    theme_classic() +
    theme(aspect.ratio=1, legend.position="none") +
    geom_hline(yintercept=0, linetype="dashed") +
    coord_flip() +
    ggtitle("Quadratic")

resQuad %>%
  mutate( p.value = format(p.value, scientific=TRUE)) %>%
  kbl %>% 
  kable_classic(full_width = FALSE)
```

### Estimate somatic rate per donor
```{r ranef}
df = lapply(resList, function(x){

  # predictions at sample level 
  pred = predict(x$fit0, se.fit = TRUE)

  # predictions at donor level, centered at zero
  ran = ranef(x$fit0, condVar=TRUE)
  se = attr( ran$cond$SubID.x, "condVar")
  SomaticRate = ran$cond$SubID.x$`(Intercept)`

  # dsgn = model.matrix()


  # predictions at donor level, centered at zero
  SomaticRate = rowSums(coef(x$fit0)$cond$SubID.x) #- fixef(x$fit0)$cond[1]
  # plot(SomaticRate, ran$cond$SubID.x$`(Intercept)`)

  # newdata = data %>%
  #           group_by(SubID.x, CellType) %>%
  #           summarize(no_cells = sum(no_cells), no_reads = sum(no_reads), Callable_Sites = sum(Callable_Sites)) %>%
  #           filter(CellType == x$CellType)

  # i = match( rownames(ran$cond$SubID.x), newdata$SubID.x)
  # newdata = newdata[i,]

  # pred = predict(x$fit0, newdata = newdata, se.fit = TRUE)
  # yhat = pred$fit + ran$cond$SubID.x$`(Intercept)`

  i = match(rownames(ran$cond$SubID.x), control_data$SubID.x)

  df_ranef = data.frame(Method = "ranef", 
        CellType = x$CellType, 
        SubId = rownames(ran$cond$SubID.x),
        Age = control_data$Age[i],
        SomaticRate = SomaticRate,
        se = c(attr( ran$cond$SubID.x, "condVar")))

  i = match(x$fit0$frame$SubID.x, control_data$SubID.x)

  df_pred = data.frame(Method = "pred", 
        CellType = x$CellType, 
        SubId = x$fit0$frame$SubID.x,
        Age = control_data$Age[i],
        SomaticRate = pred$fit,
        se = pred$se.fit)

  rbind(df_pred, df_ranef)
  })
df = do.call(rbind, df)
df = df %>% 
  filter( CellType != "Immune") %>%
  droplevels %>%
  mutate(CellType = factor(CellType, sort(levels(CellType))))
```

```{r plots.ranef}
df %>%
  filter( Method == "ranef") %>%
  ggplot(aes(Age, SomaticRate, weight=1/se^2)) +
  geom_point(aes(color=se)) +
  theme_classic() +
  geom_smooth(method = "lm", se=FALSE) +
  geom_smooth(method = "lm", formula = y ~ x + I(x^2), color="green3", se=FALSE) +
  theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1) +
  facet_wrap(~CellType, scale="free_y") +
  scale_color_gradient(low="grey", high="red") +
  ylab("Estimated somatic rate")
```


### Approximate results with two-step model
```{r test.of.ranef}
resLM = lapply(levels(df$CellType), function(CT){

  df2 = df %>%
    filter(CellType == CT, Method == "ranef")

  fit = lm(SomaticRate ~ Age, df2, weight = 1/se^2)
  data.frame(CellType = CT, t(coef(summary(fit))[2,]))
  })
resLM = do.call(rbind, resLM)

resLM %>%  
  rename(p.value = Pr...t..) %>%
  mutate( p.value = format(p.value, scientific=TRUE)) %>%
  kbl %>% 
  kable_classic(full_width = FALSE)
```







